# Generated by Django 5.2.9 on 2026-01-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_apply_ads', 'Can apply for ads'), ('can_answer_tickets', 'Can answer support tickets'), ('can_set_execution', 'Can set time and place for work')]},
        ),
    ]
