# Generated by Django 5.2.9 on 2026-01-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Finance', 'Finance')], default='IT', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ALLOCATED', 'Allocated'), ('PENDING_APPROVAL', 'Pending Approval'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='OPEN', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
