# Generated by Django 5.2.9 on 2026-01-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='execution_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='execution_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
