# Generated by Django 5.2.9 on 2026-01-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisement_execution_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Finance', 'Finance'), ('TECHNICAL', 'Technical'), ('SERVICE', 'Service')], default='IT', max_length=20),
        ),
    ]
