# Generated by Django 5.2.9 on 2025-12-14 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('answer', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.request')),
            ],
        ),
    ]
