# Generated by Django 5.2.9 on 2026-01-03 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisement_execution_location_and_more'),
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='request',
        ),
        migrations.AddField(
            model_name='ticket',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='advertisements.advertisement'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
